name: werehouse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  google_fonts: ^6.1.0
  iconly: ^1.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  mysql1: ^0.20.0
  animations: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/introduction_animation/
    - assets/dashboard/
